layout_spectrum: 0.6085385
color:
  saturation: 0.7492225
  lightness: 0.3862095
  brandStrength: 0.4924472
  brandColors:
    - '#AD9788'
    - '#A24349'
    - '#42040F'
    - '#FFFFFF'
    - '#024782'
  rhythmicContrast: 0.588201
typography_spectrum: 0.2352445
name: Sammyfar
